spring.datasource.url=jdbc:postgresql://db:5432/condominio_db
spring.datasource.username=condominio_user
spring.datasource.password=condominio_pass
spring.datasource.hikari.connection-init-sql=SET search_path TO public
spring.flyway.schemas=public
spring.flyway.default-schema=public
spring.flyway.repair-on-migrate=true
