spring.datasource.url=${DATABASE_URL}
spring.datasource.hikari.connection-init-sql=SET search_path TO public
spring.flyway.schemas=public
spring.flyway.default-schema=public
spring.flyway.repair-on-migrate=true
